import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { clearMacOsLocale } from './screenshots/os-locale';
import type { ScreenshotFixtures } from './screenshots/types';
import { createVideoSession } from './video/browser';
import { OUTPUT_VIDEO_DIR, VIDEO_HEIGHT, VIDEO_WIDTH } from './video/config';
import { smoothClick, smoothMoveTo, smoothSelectOption, smoothType } from './video/cursor';
import { hideOverlay, showOverlay } from './video/overlay';
import { videoScenarios } from './video/scenarios';
import type { VideoContext } from './video/types';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function isFfmpegAvailable(): boolean {
  try {
    execSync('ffmpeg -version', { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

async function main(): Promise<void> {
  const extensionPath = path.resolve('.output/chrome-mv3');
  if (!fs.existsSync(extensionPath)) {
    throw new Error(`Extension build not found at ${extensionPath}. Run "pnpm build" first.`);
  }

  const fixturesDir = path.resolve(__dirname, 'fixtures');
  const fixtures: ScreenshotFixtures = {
    json: fs.readFileSync(path.join(fixturesDir, 'sample.json'), 'utf-8'),
    html: fs.readFileSync(path.join(fixturesDir, 'sample.html'), 'utf-8'),
    font: fs.readFileSync(path.join(fixturesDir, 'sample.ttf')),
  };

  fs.mkdirSync(OUTPUT_VIDEO_DIR, { recursive: true });

  console.log(`🎬 Starting automated demo video recording (${VIDEO_WIDTH}x${VIDEO_HEIGHT})...`);
  console.log(`📋 Total scenarios to execute: ${videoScenarios.length}\n`);

  const session = await createVideoSession(extensionPath, fixtures);

  const ctx: VideoContext = {
    page: session.page,
    extensionId: session.extensionId,
    fixtures,
    showOverlay: async (opts) => showOverlay(session.page, opts),
    hideOverlay: async () => hideOverlay(session.page),
    smoothMoveTo: async (loc, duration) => smoothMoveTo(session.page, loc, duration),
    smoothClick: async (loc) => smoothClick(session.page, loc),
    smoothType: async (loc, text, delay) => smoothType(session.page, loc, text, delay),
    smoothSelectOption: async (loc, val) => smoothSelectOption(session.page, loc, val),
    sleep: async (ms) => session.page.waitForTimeout(ms),
  };

  try {
    for (let i = 0; i < videoScenarios.length; i++) {
      const scenario = videoScenarios[i];
      console.log(`🎥 [${i + 1}/${videoScenarios.length}] Running ${scenario.name}...`);
      await scenario.run(ctx);
    }

    console.log('\n🏁 Finished all scenarios. Finalizing video recording...');
    await ctx.sleep(1500);
  } finally {
    clearMacOsLocale();
  }

  const rawVideoPath = await session.close();

  if (!rawVideoPath || !fs.existsSync(rawVideoPath)) {
    throw new Error('Video file was not generated by Playwright.');
  }

  const outputWebm = path.join(OUTPUT_VIDEO_DIR, 'source-viewer-demo.webm');
  fs.copyFileSync(rawVideoPath, outputWebm);
  console.log(`\n✅ High-definition WebM video saved to:\n   ${outputWebm}`);

  if (isFfmpegAvailable()) {
    const outputMp4 = path.join(OUTPUT_VIDEO_DIR, 'source-viewer-demo.mp4');
    console.log(`\n🎞️ Converting to MP4 via ffmpeg...`);
    try {
      execSync(
        `ffmpeg -y -i "${outputWebm}" -c:v libx264 -pix_fmt yuv420p -preset medium -crf 20 -movflags +faststart "${outputMp4}"`,
        { stdio: 'inherit' },
      );
      console.log(`✅ MP4 video generated:\n   ${outputMp4}`);
    } catch (err) {
      console.warn('⚠️ Warning: ffmpeg MP4 conversion encountered an issue:', err);
    }
  } else {
    console.log('\nℹ️ Tip: ffmpeg is not installed. The .webm video is ready for use on YouTube and Chrome Web Store.');
    console.log('   (To produce MP4 files, install ffmpeg with: brew install ffmpeg)');
  }

  console.log('\n🎉 Demo video generation completed successfully!');
}

main().catch((err) => {
  console.error('❌ Error generating demo video:', err);
  clearMacOsLocale();
  process.exit(1);
});
